name: mc_crud_test
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # BLoC for state management
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

  # Freezed for creating unioin entities
  freezed_annotation: ^1.1.0

  # Json annotation for combine json methods to our models
  json_annotation: ^4.4.0

  # Hive for storing data & Database
  hive: ^2.0.6
  hive_flutter: ^1.1.0

  # Path provider for OS-specific directory path
  path_provider: ^2.0.9

  # Functional programming things like `Either` and ...
  dartz: ^0.10.1

  # Get it for service locator
  get_it: ^7.2.0

  # Validators
  email_validator: ^2.0.1


  # This one created buy flutter :)
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Mockito for creating mock data
  mockito: ^5.1.0

  # Hive Generator is an extention for `Hive` to generate data
  hive_generator: ^1.1.2

  # Freezed for creating unioin entities
  freezed: ^1.1.1

  # Json serializable for combine json methods to our models
  json_serializable: ^6.1.5

  # Build runner to let other packages like `Hive` or `Freezed` generate theire data
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  # Project assets :)
  assets:
    - assets/images/

  # Projects fonts
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Light.ttf
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 700
