name: mc_crud_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  freezed_annotation: ^1.1.0
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  mockito: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Light.ttf
        - asset: fonts/Fredoka-Regular.ttf
          weight: 500
        - asset: fonts/Fredoka-SemiBold.ttf
          weight: 700
